@startuml

left to right direction
skinparam packageStyle rectangle

actor "**Клиент**" as User
actor "**Гость**" as Guest

rectangle "Сервис поиска потенциальных клиентов VK" as Clients-finder {
    Guest --> (**Регистрация**)
    Guest --> (**Авторизация**)

    User --> (**Выход**)
    User --> (**Просмотр созданных поисковых задач**)

    User --> (**Просмотр результата поисковой задачи**)
    (**Просмотр результата поисковой задачи**) ..> (**Удаление поисковой задачи**) : включает
    (**Просмотр результата поисковой задачи**) ..> (**Удаление определенных клиентов**) : включает
    (**Просмотр результата поисковой задачи**) ..> (**Добавление определенных клиентов в избранное**) : включает
    (**Просмотр результата поисковой задачи**) ..> (**Фильтрация клиентов по не закрытым аккаунтам**) : включает

    User --> (**Просмотр списка клиентов в избранном**)
    (**Просмотр списка клиентов в избранном**) ..> (**Удаление клиента из избранного**) : включает
    (**Просмотр списка клиентов в избранном**) ..> (**Фильтрация клиентов по не закрытым аккаунтам**) : включает

    User --> (**Создание поисковой задачи**)
    (**Создание поисковой задачи**) ..> (**Ввод ограничений**) : включает
    (**Ввод ограничений**) ..> (**по полу**) : включает
    (**Ввод ограничений**) ..> (**по возрасту**) : включает
    (**Ввод ограничений**) ..> (**по году рождения**) : включает
    (**Ввод ограничений**) ..> (**по месяцу рождения**) : включает
    (**Ввод ограничений**) ..> (**по дню рождения**) : включает
    (**Ввод ограничений**) ..> (**по семейному статусу**) : включает
    (**Ввод ограничений**) ..> (**по наличию фотографии**) : включает
    (**Ввод ограничений**) ..> (**по городу**) : включает
    (**Ввод ограничений**) ..> (**по университету**) : включает
    (**Создание поисковой задачи**) ..> (**Ввод ключевых фраз**) : включает
}

@enduml